### ISSUE TITLE
[request] customize role count

### ISSUE THREAD

**Issue by cakcaraka** [tulul/lycantulul_bot#3]
It will be appreciated if we (user in a group), can modify the role count before starting a game. because sometimes, we feel the role distribution is not fair enough.

Illustration: 6 players
Default:
- one werewolf
- one seer
- four villager

we would love to sometimes change\* the distribution to:
- two werewolves
- one seer
- three villagers
  *only an example

Is it possible?

**Comment by araishikeiwai** [comment]
considered. this includes customization of night/voting times.

after #4
